### ISSUE TITLE
If user forget to input expiry month, done button will crash the app

### ISSUE THREAD

**Issue by walterhuangfs** [MobileFirstInc/MFCard#12]
First of all, thank you for putting up this awesome library. It looks really good.

If 'done' button shows up and expiry month is not correctly input, the app crashed on this line:

 card = Card(holderName: txtCardName.text, number: cardNumber, month: Month(rawValue: viewExpiryMonth!.labelValue.text!)!, year: viewExpiryYear!.labelValue.text!, cvc: txtCvc.text!, paymentType: Card.PaymentType.card, cardType:addedCardType!, userId: 1)

Month takes certain input, and the default string 'MM' is not one of them.

**Comment by arpandesai** [comment]
Thank you for your appreciation. We will fix it today 👍🏻

-- Arpan Desai 
+91 999 875-5114

**Comment by RC7770** [comment]
Thanks @walterhuangfs for your review. We fixed it and closing this issue now 👍🏻

**Comment by walterhuangfs** [comment]
That will do it! Thank you guys for the fast turnaround time.
