### ISSUE TITLE
'Card' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by FranciscoMkdir** [MobileFirstInc/MFCard#13]
I have this error:  'Card' is ambiguous for type lookup in this context.
In this method:
```
func cardDoneButtonClicked(_ card: Card?, error: String?) {
}

```

**Comment by arpandesai** [comment]
We will try fix the same by tomorrow.

Thank you. 

-- Arpan Desai 
+91 99987 55114

**Comment by RC7770** [comment]
@FranciscoMkdir : can you please provide dummy data for test or share the use case for this ?
and can you add print(card), print(error) will help as to understand!

Thanks.

**Comment by FranciscoMkdir** [comment]
My fault, I did not realize that I installed another library that has a 'Card' class with the same name.

**Comment by RC7770** [comment]
Ohh, no worries @FranciscoMkdir 
feel free to share your reviews.

now i'm Closing this issue.
Thanks.
