### ISSUE TITLE
 month year did not open

### ISSUE THREAD

**Issue by mohayoub** [MobileFirstInc/MFCard#14]
year month did not open picker

When click

waring in debug is :

animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

**Comment by mohayoub** [comment]
[Warning] <UIVisualEffectView 0x102bf97a0> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

**Comment by mohayoub** [comment]
Please help

**Comment by arpandesai** [comment]
Hello @mohayoub - A team member will help you resolve the issue in next 12 to 18 hours. Thank you. 

@RC7770 - can you check this.

**Comment by mohayoub** [comment]
Thank you I am waiting...

**Comment by RC7770** [comment]
hey @mohayoub : we fixed the warring - "animate its opacity. This will cause the effect to appear broken until opacity returns to 1."

but year and month spinner is working fine, can't reproduce same here. 

can you try again with latest pod version or just download the demo ?

if you still getting same issue, let us know the way your implementing MFCard.

Always here to help you 
Thanks!

**Comment by mohayoub** [comment]
Today we are in August 2017  the spinner display Jun July.... 2017
we need old month did not display

**Comment by mcconkiee** [comment]
i'm still not seeing the spinners for month or year

**Comment by arpandesai** [comment]
Hello Eric,

We will push an update soon. 

-- Arpan Desai 
+91 99987 55114
